### PR TITLE
Add attachments messages capabilities

### PR DESCRIPTION
**Pull request by nerlichman**
Four new actions were added to the slack platform

I opened this PR as a preview of the functionality.
Documentation it's not finished nor it's reviewed and it lacks test cases.

### CODE REVIEW

**Comment by gdaniel** [comment]
Hi @nerlichman, what is the current status of the pull request? Let me know if I can help with anything

**Comment by nerlichman** [comment]
I'm sorry @gdaniel I thought I was going to have free time this week to finish it but I got caught up in work.

**Comment by gdaniel** [comment]
Hi,

I took a look at your request and it looks fine to me, excepted two points I'd like to clarify
- does it always make sense to provide a timestamp for an attachment? If most of the time the timestamp is today's date we can maybe add another action without this parameter, and fill it automatically.
- I don't see how the constructor with the `Attachment` parameter type can be called, since we don't have any action returning `Attachment` instances. Anyway, I wouldn't remove this constructor, because we may have such action in the future.

Really nice work 😃

**Comment by nerlichman** [comment]
Hi!,

- Great, I'll make another one without timestamp input 

- This constructor is meant to be used to integrate reponses from other platforms, as used in the Twitter Platform. In this example a Twitter action outputs a list of attachments that is sent to Slack through this constructor. Besides this example, I think this could prove to be useful in other cases in the future.

**Comment by gdaniel** [comment]
Thanks! 

Ok, I'll take a look at the integration with your Twitter platform when it will be available then. Anyway you are right, this can be useful in other contexts, and we should definitely keep it.

**Comment by nerlichman** [comment]
@gdaniel  as you proposed, I created another version for the actions that sets the timestamp to the actual date.

I haven't been able to try it because I'm having some problems to make the chatbot work after the changes from Jarvis to Xatkit

**Pull request merged**
